name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      
      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew
      
      # Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Upload build artifacts (e.g., JAR file)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/libs/*.jar
      
      # Test with Gradle
      - name: Test with Gradle
        run: ./gradlew test

      # Optionally, upload test reports
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/tests/test/*
